# Header
menu:
  å½’æ¡£: /archives
rss: /atom.xml
title: ğŸ±Home

author: Guile Ho
aboutme: Hi~

# Content
excerpt_link: å…¨æ–‡...
fancybox: true
date_format: 'YYYYå¹´MMæœˆDDæ—¥'

socials:
  github: "https://github.com/fuguimashu"
  email: "fuguimashu@gmail.com"
  wechat: "heguile"



# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

#ä¸»é¢˜æ–¹æ¡ˆ
highlight_theme: atom light

# widget behavior
archive_type: 'monthly'
show_count: false

disqus_shortname:

# Miscellaneous
google_analytics: 'UA-61220413-1'
gauges_analytics:
favicon: /images/avatar.png
avatar: "/images/avatar.png"
twitter:
google_plus:
fb_admins:
fb_app_id:
